# Generated by Django 5.0.1 on 2024-01-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_admin_age_remove_admin_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='days',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='height',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='historyOfBloodPressure',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='historyOfDiabetes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weight',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False),
        ),
    ]
