# Generated by Django 5.0.1 on 2024-01-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_admin_experience_remove_customer_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='idEmpoy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
