# Generated by Django 5.0.1 on 2024-01-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_admin_idempoy_alter_admin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='idEmpoy',
            new_name='idEmploy',
        ),
    ]
