# Generated by Django 5.0.1 on 2024-01-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_admin_age_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False, unique=True),
        ),
    ]
